### ISSUE TITLE
Support multiple clients of the same type

### ISSUE THREAD

**Issue by Saviq** [canonical/sbomber#26]
For completeness, it might be run a scan with different scanners. Would be good to either support:

```
clients:
  secscan:
    scanner: [trivy, osv]
```

Or maybe simpler:
```
clients:
  trivy:
    type: secscan
    scanner: trivy
  osv:
    type: secscan
    scanner: osv
```
