### ISSUE TITLE
Allow overriding clients per artifact

### ISSUE THREAD

**Issue by Saviq** [canonical/sbomber#27]
Related to #26, would be good to allow overriding scanners per artefact:

```yaml
clients:
  secscan: {}
  sbom: {}

artifacts:
- name: foobar
  clients:
    secscan:
      scanner: "osv"
```
